root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/server/main.go"
  bin = "./tmp/main"
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "postgres-data"]
  include_ext = ["go", "tpl", "tmpl", "html", "env"]
  delay = 1000 # ms
  stop_on_error = true

[log]
  time = true

[misc]
  clean_on_exit = true