name: Geo Engine CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Create .env file from example
      run: cp .env.example .env

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Debug Docker Config
      run: docker compose config

    - name: Start Custom Database
      run: |
        docker compose up -d --build db 
        
        echo "Waiting for Database to be ready..."
        sleep 10
        until docker exec geo-postgres pg_isready -U geo; do
          echo "Waiting for DB..."
          sleep 2
        done
        echo "Database is ready!"

    - name: Install golang-migrate
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.16.2/migrate.linux-amd64.tar.gz | tar xvz
        sudo mv migrate /usr/local/bin/

    - name: Run Migrations
      run: make migrate-up
      env:
        DB_URL: postgres://geo:secretpassword@localhost:5432/geoengine?sslmode=disable
    - name: Test Backend
      run: make test-backend